[package]
name = "yksisim"
version = "0.1.0"
edition = "2021"

[lib]
name = "yksisim"
path = "src/lib.rs"

[[bin]]
name = "yksi-simulate"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
